### ISSUE TITLE
App crashes after altering sources in the settings menu

### ISSUE THREAD

**Issue by khushaljobanputra** [EntireNewsProject/Android-App#12]
When we go to select sources under the settings menu and change sources that are shown then the app crashed when going back to the app home page.

Below is the instructions to recreate the bug.

Homepage --> Settings Menu --> Select Sources --> Change few displayed sources --> Click back to go to settings page--> Click back to go to home page --> !!!App crashed!!!

**Comment by shifatul-i** [comment]
Fixed
